steps:
  - name: python:${_PYTHON_VERSION}
    id: Security and stylish linter test
    entrypoint: bash
    args:
    - '-c'
    - |
       pip3 install bandit pylint && \
       echo =====PYLINT==== && \
       pylint --exit-zero *.py && \
       echo =====BANDIT==== && \
       if [[ "${_BANDIT_VERBOSE}" == "true" ]]
        then
          echo "=====RUNNING BANDIT WITH VERBOSITY====="
          bandit -r ${_BANDIT_TESTING_LEVEL} -v .
        else
          bandit -r ${_BANDIT_TESTING_LEVEL} .
        fi
  - name: gcr.io/cloud-builders/docker
    id: Build
    entrypoint: bash
    args:
    - '-c'
    - |
        docker build -t ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${SHORT_SHA} .

  - name: gcr.io/cloud-builders/docker
    id: Push
    entrypoint: bash
    args:
    - '-c'
    - |
       docker push ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${SHORT_SHA}
       
substitutions:
  _REGISTRY_: us-central1-docker.pkg.dev/test-cloudbuild-8712/demo-registry
  _APPNAME_: simplepythonapp
  _ENV_: dev
  _PYTHON_VERSION: 3.6
  _BANDIT_TESTING_LEVEL: -lll
  _BANDIT_VERBOSE: "false"
