steps:
 - name: gcr.io/cloud-builders/docker
   id: Build
   entrypoint: bash
   args:
   - '-c'
   - |
       docker build -t ${REGISTRY}/${APPNAME}:${ENV}-${SHORT_SHA} .

 - name: gcr.io/cloud-builders/docker
   id: Push
   entrypoint: bash
   args:
   - '-c'
   - |
       docker push ${REGISTRY}/${APPNAME}:${ENV}-${SHORT_SHA}
       
substitutions:
  _REGISTRY_: us-central1-docker.pkg.dev/test-cloudbuild-8712/demo-registry
  _APPNAME_: simplepythonapp
  _ENV_: dev
