apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app.fullname" . }}
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-app.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "demo-app.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: config-data
            mountPath: /data
      volumes:
      - name: config-data
        emptyDir: {}
      initContainers:
      - name: secrets
        image: gcr.io/google.com/cloudsdktool/cloud-sdk
      args: 
      - echo "API_KEY=$(gcloud secrets versions access latest --secret=\"api_key\")" >> super_secret.env
      volumeMounts:
      - name: config-data
        mountPath: /data
