apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-flask-app.fullname" . }}
  labels:
    {{- include "sample-flask-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sample-flask-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sample-flask-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: test-eso-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: key-vol
            mountPath: /vol
      volumes:
      - name: key-vol
        emptyDir: {}
      initContainers:
      - name: get-secrets
        image: gcr.io/google.com/cloudsdktool/cloud-sdk
        command:
        - /bin/sh
        - -c
        - |
          API_KEY=$(gcloud secrets versions access latest --secret="api_key")
          echo $API_KEY
          mkdir -p /vol
          touch /vol/api_key.pem
          echo $API_KEY >> /vol/api_key.pem
          mv /vol/api_key.pem /vol/api_key
        volumeMounts:
        - mountPath: /vol
          name: key-vol
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
